### ISSUE TITLE
Add support for torrent labels

### ISSUE THREAD

**Issue by harchani-ritik** [CCExtractor/rutorrent-flutter#10]

**Comment by cyber-venom003** [comment]
@harchani-ritik I would like to work on this! 😃

**Comment by santhoshivan23** [comment]
@harchani-ritik I'd like to work on this. Could you please provide me with a brief description of the enhancement required? Thanks!

**Comment by harchani-ritik** [comment]
@santhoshivan23 
Initially, you can work on just adding a new label on a torrent and removing it.
There should be an option (just like filters-expandable) in a navigation-drawer showing all labels and torrents labelled to them.

**Comment by imanishbarnwal** [comment]
Hye @santhoshivan23 is this still opened to contribute? Let me know if I can work on this thank you. :)

**Comment by santhoshivan23** [comment]
@imanishbarnwal Yes, you can! I was waiting for the API documentation for labels but I guess it's taking time. You could coordinate with @harchani-ritik Thanks!

**Comment by PaRaDoX50** [comment]
Hey @harchani-ritik ! Is someone working on this? If not, you may assign this to me. Thanks!
