### ISSUE TITLE
state management issue in torrent_list_page

### ISSUE THREAD

**Issue by rj-since-2000** [CCExtractor/rutorrent-flutter#106]
The root widget of TorrentsListPage is `Consumer<GeneralFeatures>`. Not mentioning all the functions inside GeneralFeatures, the two specific functions `updateDiskSpace()` and `setListOfLabels()` also notify change in the `Consumer<GeneralFeatures>` as usual. One of these two functions is getting called over a stream `getAllAccountsTorrentList()` in ApiRequests. Both the functions mentioned earlier are not utilised in the TorrentsListPage but because of these the `Consumer<GeneralFeatures>` is providing change very frequently in the tree which is causing widget rebuild a lot more number of times than it should actually build. The actual use of these two functions is in the Drawer. All this occurred when the torrent list was not empty. 

@harchani-ritik I would like to work on this. A simple solution I thought was to create a separate class of ChangeNotifier from GeneralFeatures so that functions used inside other widgets only consume providers needed. Also mention any suggestion from your side.

**Comment by harchani-ritik** [comment]
`A simple solution I thought was to create a separate class of ChangeNotifier from GeneralFeatures so that functions used inside other widgets only consume providers needed`
This approach seems good, @rj-since-2000 . Please go ahead.

**Comment by rj-since-2000** [comment]
I'm closing this issue. This issue will be resolved in the new architecture in dev branch.
