### ISSUE TITLE
Feature to add torrent file via file explorer

### ISSUE THREAD

**Issue by harchani-ritik** [CCExtractor/rutorrent-flutter#11]

**Comment by cyber-venom003** [comment]
@harchani-ritik I would like to work on this.

**Comment by cyber-venom003** [comment]
@harchani-ritik  
![ruTorrent_issue](https://user-images.githubusercontent.com/58390399/96227712-1c666500-0fb2-11eb-941c-a82564dedf83.gif)

Should I make the PR for this??
