### ISSUE TITLE
State of the Torrents list page inside PageView dies on navigating to another page

### ISSUE THREAD

**Issue by rj-since-2000** [CCExtractor/rutorrent-flutter#111]
Upon navigating to one page in the PageView, the states of other pages are not saved which causes a halt in the Torrents list page as the entire widget tree is rebuilt.

https://user-images.githubusercontent.com/68644104/111707106-7b821b80-8869-11eb-9d67-070dd3bcbee0.mp4

@harchani-ritik I would like to solve this issue using `AutomaticKeepAliveClientMixin()`.

**Comment by pratikbaid3** [comment]
@rj-since-2000 I wouldn't suggest doing this, since we are using stream builders to constantly keep the page updated, adding this mixin will make the data static.
