### ISSUE TITLE
Doubt regarding File Structure

### ISSUE THREAD

**Issue by AbdulMalikDev** [CCExtractor/rutorrent-flutter#117]
I have a few doubts about the applications, hope they can be answered.

What is the difference between having a **pages** folder and a **screens** folder for the application ?

I might be confused here but there is a folder called **services** but most of the logic tends to be written in the UI files itself. Is there something about the architecture i am missing out on?

For example in the ``` settings_screen.dart``` file the code for deleting an account, logging out of an account and changing the password all are in the same file.

Usually i use [the Stacked Architecture](https://github.com/FilledStacks/stacked) with clear UI and logic seperation, so just wanted to know the architecture the application is following. Would love to have a discussion with the moderators @cfsmp3 and @harchani-ritik  if using stacked architecture can be an option.

**Comment by harchani-ritik** [comment]
@AbdulMalikDev 
So, the convention I used here was widgets in **pages** were placed horizontally with each other on the navigation stack and those in **screens** were placed vertically.
This stacked architecture looks good though, surely, the code can be refactored according to this, you can elaborate on the advantages of using this architecture in your proposal and yes, we surely have a discussion regarding this.

**Comment by AbdulMalikDev** [comment]
> @AbdulMalikDev 
> So, the convention I used here was widgets in **pages** were placed horizontally with each other on the navigation stack and those in **screens** were placed vertically.
> This stacked architecture looks good though, surely, the code can be refactored according to this, you can elaborate on the advantages of using this architecture in your proposal and yes, we surely have a discussion regarding this.
> 

Thank you for replying. Now i understand the pages and screens folder. 

Regarding the Stacked Architecture i would love to elaborate and take the responsibility of migrating the application, if it has been chosen.
