### ISSUE TITLE
Configurations screen doesn't handle username & password properly

### ISSUE THREAD

**Issue by tusharojha** [CCExtractor/rutorrent-flutter#131]
## Description

In configurations screen, one can enter any set of username & password with the URL of ruTorrent backend.

For example:

- I entered random username & password with the URL of ruTorrent backend.
- It navigates to the `main_screen` with no error message.
- I am able to see disk space used & available but the torrent list doesn't show up but the following error message logs:
 ```
  Warning: XMLRPC call is failed.
```

__Note__: I am using docker image without setting any username & password, which means it's okay if it displays the disk space but we should not use the disk space endpoint for the configurations screen rater something like `httpRpcPluginUrl` would work.

I am working on it and will create a PR soon.

**Comment by AbdulMalikDev** [comment]
The project has been updated extensively in the last 2 years (check [wiki ](https://github.com/CCExtractor/rutorrent-flutter/wiki)for more info). The default branch is now the "main" branch. All issues for previous versions are being removed.
