### ISSUE TITLE
Breaking Change: Insecure HTTP connections are disabled by default on iOS and Android.

### ISSUE THREAD

**Issue by PaRaDoX50** [CCExtractor/rutorrent-flutter#15]
There are some breaking changes in the flutter's network policy : [https://flutter.dev/docs/release/breaking-changes/network-policy-ios-android](url)

Because of these changes, the app even on putting a right URL in the location field gives a "Invalid" toast.

In general the local host runs on HTTP. So we need to allow the use of http connections in debug builds.

**Comment by cyber-venom003** [comment]
@PaRaDoX50 can you assign this to me?? As far as I've understood this issue, all I need to do is 
```
<meta-data android:name="io.flutter.network-policy"
             android:resource="@xml/network_security_config"/>
```
Add this above line to network_security_config.xml for the android app.

**Comment by PaRaDoX50** [comment]
> @PaRaDoX50 @harchani-ritik can you assign this to me?? As far as I've understood this issue, all I need to do is
> 
> ```
> <meta-data android:name="io.flutter.network-policy"
>              android:resource="@xml/network_security_config"/>
> ```
> 
> Add this above line to network_security_config.xml for the android app.

Actually, there are couple of ways to do it. We can either edit the Network Config file and add the code you sent above to the manifest file,  if we want to allow HTTP connection for  some specific domains or we can add one single attribute to the application tag to the manifest file if we want it for every address. 
We need to edit the debug manifest file since we should only allow unsecure connection in debug mode.
Actually I was going to send a PR. I hope you don't mind.

**Comment by cyber-venom003** [comment]
@PaRaDoX50 ya no issue, please go ahead🙂

**Comment by harchani-ritik** [comment]
@PaRaDoX50  Thanks for pointing out and fixing this.
