### ISSUE TITLE
Splash screen appears white even in dark theme

### ISSUE THREAD

**Issue by curiousyuvi** [CCExtractor/rutorrent-flutter#155]
The Splash Screen appears white even in dark theme which contradicts the UI.
![rutorrent_splash_screen_issue](https://user-images.githubusercontent.com/58589519/142818242-65dbda62-3e34-44c7-9e34-5bf6f61cf8f7.gif)
I'm very new to open source, therefore I would like to be assigned to this small issue.

**Comment by AbdulMalikDev** [comment]
The project has been updated extensively in the last 2 years (check [wiki ](https://github.com/CCExtractor/rutorrent-flutter/wiki)for more info). The default branch is now the "main" branch. All issues for previous versions are being removed.
