### ISSUE TITLE
Deprecated Member Use 

### ISSUE THREAD

**Issue by M-A-D-A-R-A** [CCExtractor/rutorrent-flutter#157]
`accent color` is deprecated in many files.

I would like to migrate to 
`colorScheme: ColorScheme.fromSwatch().copyWith(secondary: "Secondary Color")`

Please assign it to me. Thanks

**Comment by AbdulMalikDev** [comment]
The project has been updated extensively in the last 2 years (check [wiki ](https://github.com/CCExtractor/rutorrent-flutter/wiki)for more info). The default branch is now the "main" branch. All issues for previous versions are being removed.
