### ISSUE TITLE
Mapping Warning while building app

### ISSUE THREAD

**Issue by ItsAdityaKSingh** [CCExtractor/rutorrent-flutter#159]
**Numerous mapping warnings are thrown on the console while building the app.**

<img width="993" alt="Screenshot 2022-01-16 at 2 56 38 AM" src="https://user-images.githubusercontent.com/69353350/149638402-cca6eb95-8424-4192-8bf7-1409fdefc848.png">

**Comment by AbdulMalikDev** [comment]
The project has been updated extensively in the last 2 years (check [wiki ](https://github.com/CCExtractor/rutorrent-flutter/wiki)for more info). The default branch is now the "main" branch. All issues for previous versions are being removed.
