### ISSUE TITLE
Too many Positional Arguments

### ISSUE THREAD

**Issue by ItsAdityaKSingh** [CCExtractor/rutorrent-flutter#163]
Extra positional arguments for AndroidNotificationDetails causing error while running.

<img width="993" alt="Screenshot 2022-01-16 at 3 16 29 AM" src="https://user-images.githubusercontent.com/69353350/149638749-23067d7b-746d-4895-ae58-05848167c83c.png">

Although there's no error in building, but still it shows this message in debug console.

**Comment by AbdulMalikDev** [comment]
This issue has been solved.
