### ISSUE TITLE
Cannot log in

### ISSUE THREAD

**Issue by ghost** [CCExtractor/rutorrent-flutter#173]
Cannot log in on all browsser goes without problem but here on app just does not work

It always comes username or password not correct

Url: https://hd*****e.org
User: mronyx
Pass: ***************

User and password is 100% correct
And also have no special characters

**Comment by buildwithmalik** [comment]
Try adding a "/rtorrent/" at the end of the URL. For example the URL I use is "https://\<Server URL\>/rtorrent/"
