### ISSUE TITLE
Improve code formatting for dart files

### ISSUE THREAD

**Issue by tusharojha** [CCExtractor/rutorrent-flutter#23]
As of now, almost all the dart files are not formatted properly according to base dart rules. We can use the `dart format` command to format all the files. Having a properly formatted code will help people to understand the project more easily and thus more contributing.

Let me know if this issue seems worth it to be addressed, I would like to land my first PR for this issue.

**Comment by harchani-ritik** [comment]
Yeah sure, go-ahead.

**Comment by harchani-ritik** [comment]
@tusharojha Thanks for the contribution, please make sure of the commit message style as mentioned in contributing guidelines for future contributions.
