### ISSUE TITLE
Torrent Details Screen crashes after download completes, if navigated from "Downloading" Filter 

### ISSUE THREAD

**Issue by harchani-ritik** [CCExtractor/rutorrent-flutter#26]
Steps to reproduce:
1) Start a torrent download.
2) Switch to 'downloading' filter from the navigation drawer.
3) Click on the torrent tile to open the torrent details screen.
4) Wait for the download to complete and boom! you see a "red screen of death" :(

![error-gif](https://user-images.githubusercontent.com/46641571/105955729-bacb9180-609c-11eb-807c-30b7a6b9ed7d.gif)

**Comment by pratikbaid3** [comment]
Id like to work on this @harchani-ritik

**Comment by OnyemaAnthony** [comment]
i will like to also work on this, must the torrent download to 100 percent before the error is show? @harchani-ritik

**Comment by pratikbaid3** [comment]
@OnyemaAnthony I am already working on this and will be making a pr soon.

**Comment by OnyemaAnthony** [comment]
Okay

**Comment by pratikbaid3** [comment]
#32

**Comment by harchani-ritik** [comment]
@pratikbaid3 Thanks for solving this.
