### ISSUE TITLE
enhancement

### ISSUE THREAD

**Issue by OnyemaAnthony** [CCExtractor/rutorrent-flutter#30]
remove the red debug banner and also when a user what to login and there is an error it show invalid, i want to add a more meaningful error message instead of invalid,please can i proceed?

**Comment by harchani-ritik** [comment]
@OnyemaAnthony The red debug banner depicts that app is running on debug mode and using JIT (Just-In-Time) compiler rather than AOT (Ahead-Of-Time) compiler as in release mode. So that stays, and yes you can work on improving the error toast message and make it more comprehensive.

**Comment by OnyemaAnthony** [comment]
okay i will send a PR soon
