### ISSUE TITLE
Jank while switching to dark mode

### ISSUE THREAD

**Issue by sbis04** [CCExtractor/rutorrent-flutter#33]
I noticed a jank (noticeable on the `AppBar`) while switching from light mode to dark mode and vice versa.

<img src="https://user-images.githubusercontent.com/43280874/107353048-98049880-6af2-11eb-843e-5e2e8b640557.gif" width="350"/>

**Comment by pratikbaid3** [comment]
@sbis04 This is a performance issue that occurs in debug mode. You could alternatively try building the apk and installing it, the performance is a lot better in release mode.

**Comment by sbis04** [comment]
@pratikbaid3 yes, I know that it is not noticeable in the release mode. But I still think it is a bug, which I have already found in the code and can be fixed easily. It's due to the brightness configuration of `AppBarTheme` which causes the AppBar to be white for a moment.

After fixing:
<img src="https://user-images.githubusercontent.com/43280874/107355428-735df000-6af5-11eb-85f9-a750eb2bcfab.gif" width="350"/>

I'll send a PR soon.
