### ISSUE TITLE
Remove "Browse Torrent File" option from bottom sheet in Feeds page

### ISSUE THREAD

**Issue by harchani-ritik** [CCExtractor/rutorrent-flutter#35]
![Webp net-resizeimage (3)](https://user-images.githubusercontent.com/46641571/107396621-f138f000-6b23-11eb-870e-20fee0e13dc6.png)

The bottom sheet I am referring to here is the one that opens up when we click on the centre Floating Action Button.

**Comment by Adityabhaumik** [comment]
@harchani-ritik May I have a go at it?

**Comment by harchani-ritik** [comment]
@Adityabhaumik Yeah sure, go ahead.

**Comment by harchani-ritik** [comment]
Please Note: This issue requires to remove the "Browse Torrent File" option from the bottom sheet on **ONLY** Feeds page and not on the Home page. Since on the home page, the FAB button allows users to add torrent file/link whereas on the feeds page it is concerned with adding RSS links and thus "browsing file" option there doesn't make sense and thus it needs to be removed.
