### ISSUE TITLE
Add confirmation dialog for logout

### ISSUE THREAD

**Issue by tusharojha** [CCExtractor/rutorrent-flutter#41]
## Description

As of now, the app logs out all accounts immediately by pressing the Logout button on the settings page. Ideally, It should ask for confirmation about the action since the user might accidentally tap the button.

I propose to add a confirmation dialog (AlertDialog) to prevent accidental clicks.

**Comment by tusharojha** [comment]
I am willing to add the feature.
@harchani-ritik Let me know if it's worth adding it.

**Comment by harchani-ritik** [comment]
Yeah sure, it's worth adding, you can work on this.
