### ISSUE TITLE
Empty torrent list causing the shimmer effect to appear again and again

### ISSUE THREAD

**Issue by pratikbaid3** [CCExtractor/rutorrent-flutter#5]
![Animated GIF-downsized](https://user-images.githubusercontent.com/52864956/93024408-f85edf00-f613-11ea-94ea-f5a178547fca.gif)

The getTorrentList is returning null when there is no active torrent which is causing the shimmer effect to appear again and again

Log: flutter: Exception caught in Api Request NoSuchMethodError: Class 'List<dynamic>' has no instance getter 'keys'.
Receiver: Instance(length:0) of '_GrowableList'
Tried calling: keys

**Comment by pratikbaid3** [comment]
#6 
Fixed the issue and refactored the code

**Comment by cv692001** [comment]
Hey @pratikbaid3 , can I contribute to this :)

**Comment by pratikbaid3** [comment]
Hey @cv692001. I have actually alreasy resolved the issue in #6
