### ISSUE TITLE
App crashes in Explorer screen 

### ISSUE THREAD

**Issue by MrUnfunny** [CCExtractor/rutorrent-flutter#52]
Hello Everyone,

The App currently crashes in Explorer screen in debug mode and in release [`isLoading` ](https://github.com/CCExtractor/rutorrent-flutter/blob/master/lib/screens/disk_explorer_screen.dart#L21) flag always remains true and hence shimmer will always be shown. 

This happens because there's no exception handling in [getDiskFiles](https://github.com/CCExtractor/rutorrent-flutter/blob/master/lib/api/api_requests.dart#L422).

This can be solved by handling exceptions in [getDiskFiles](https://github.com/CCExtractor/rutorrent-flutter/blob/master/lib/api/api_requests.dart#L422), return null in case of any exception and check if it returns null in [disk_explorer_screen](https://github.com/CCExtractor/rutorrent-flutter/blob/master/lib/screens/disk_explorer_screen.dart#L75).

If you find the proposed solution to be valid, I will like to send a PR.

**Comment by pratikbaid3** [comment]
Hi @MrUnfunny. I am unable to recreate the issue where the app crashes in the explorer screen. You could however try to improve the shimmer issue. @harchani-ritik 
<img width="270" alt="Screenshot 2021-02-27 at 4 52 21 PM" src="https://user-images.githubusercontent.com/52864956/109385753-32027880-791c-11eb-9eab-6b61ef7c6f43.png">

**Comment by pratikbaid3** [comment]
@MrUnfunny your proposal to add a try catch block where the api is called would fix this issue.

**Comment by MrUnfunny** [comment]
Hey @pratikbaid3
Yes, the app doesn't crash as it's an exception and not an error but it will show up in the IDE. Since the issue is due to Error Code 404 the app will not show red screen of death instead the [getDiskFiles](https://github.com/CCExtractor/rutorrent-flutter/blob/master/lib/api/api_requests.dart#L422) will throw an exception [here](https://github.com/CCExtractor/rutorrent-flutter/blob/master/lib/screens/disk_explorer_screen.dart#L23). This is the reason why `isLoading` is always set to true.
Should I send a PR or wait to be assigned?

**Comment by harchani-ritik** [comment]
The explorer option is a seedbox-only feature, but yeah it should be properly handled when rutorrent is running locally.
