### ISSUE TITLE
Improve error handling inside the app

### ISSUE THREAD

**Issue by tusharojha** [CCExtractor/rutorrent-flutter#63]
## Description

As of now, the app is expecting only good cases in which the APIs will respond with a positive message. I get to know about this issue when my `rtorrent` server was closed but still, I am able to open the app and saw a lot of error logs inside CLI but nothing on the app. 

I propose to improve the error handling inside the app which includes showing proper log messages when the app is unable to connect, showing error messages to the user about connectivity issues & some small issues too.

**Comment by harchani-ritik** [comment]
@tusharojha 
Yes, this is required. We can have a flushbar on top stating appropriate messages in cases when the Internet or rtorrent is down.

**Comment by AbdulMalikDev** [comment]
The project has been updated extensively in the last 2 years (check [wiki ](https://github.com/CCExtractor/rutorrent-flutter/wiki)for more info). The default branch is now the "main" branch. All issues for previous versions are being removed.
