### ISSUE TITLE
Adding null safety that shipped with the latest version of dart.

### ISSUE THREAD

**Issue by pratikbaid3** [CCExtractor/rutorrent-flutter#65]
The latest version of dart has a automated null safety check so migrating to null safety will allow us to not have to check for null values and this is also the default convention in the latest flutter version (V2)

@harchani-ritik I'd like to work on this.

**Comment by tusharojha** [comment]
Although, null safety is in stable from today. But as much as I remember some of our project dependencies are not migrated yet. 

I'd be great if you can confirm it using 'pub outdated' command.

**Comment by pratikbaid3** [comment]
@tusharojha I have created a separate issue migrating the dependancies to be compatible with v2. After i am done with resolving that, i'd work on the null safety issue.
