### ISSUE TITLE
Flutter V2 migration issue

### ISSUE THREAD

**Issue by pratikbaid3** [CCExtractor/rutorrent-flutter#66]
There are several issue while migrating to flutter 2.0.0

1. 
```error: The named parameter 'child' isn't defined. (undefined_named_parameter at [rutorrentflutter] lib/screens/torrent_details_screen.dart:139)```
> <img width="468" alt="Screenshot 2021-03-04 at 10 53 25 AM" src="https://user-images.githubusercontent.com/52864956/109915541-0561ae80-7cd8-11eb-807c-973761e6e1f5.png">

	

2. Flutter toast needs to be upgraded: ```In file included from /Users/pratikbaid/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-4.0.1/ios/Classes/FluttertoastPlugin.m:2:
    /Users/pratikbaid/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-4.0.1/ios/Classes/UIView+Toast.h:328:19: warning: empty paragraph passed to '@param' command [-Wdocumentation]```

3. Modal bottom sheet version outdated
```../../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/modal_bottom_sheet-0.1.6+1/lib/src/material_with_modal_page_route.dart:21:16: Error: Getter not found: 'opaque'```

4. Shared pref outdated
```pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.8/android/src/main/java/io/flutter/plugins/sharedpreferences/SharedPreferencesPlugin.java:18: warning: [deprecation] Registrar in PluginRegistry has been deprecated```

5 Raised Button
```'RaisedButton' is deprecated and shouldn't be used. Use ElevatedButton instead. See the migration guide in flutter.dev/go/material-button-migration-guide). This feature was deprecated after v1.25.0-8.1.pre. • lib/components/add_url_bottom_sheet.dart:101:22 • deprecated_member_use```

@harchani-ritik I'd like to fix this issue

**Comment by tusharojha** [comment]
Also, the `RaisedButton` and `FlatButton` is deprecated too. It's better to use `ElevatedButton` or creating a custom button for our app.

**Comment by dhruv-kabariya** [comment]
I Think for [migrate to flutter V2](https://docs.google.com/document/d/1yohSuYrvyya5V1hB6j9pJskavCdVq9sVeTqSoEPsWH0/edit#heading=h.b9pokg4cx8f9) this link might help you @pratikbaid3 .

**Comment by pratikbaid3** [comment]
Thank you @dhruv-kabariya. I'll have a look.
