### ISSUE TITLE
No (Torrent Url / Rss Url) validation while adding Torrent / Rss

### ISSUE THREAD

**Issue by rj-since-2000** [CCExtractor/rutorrent-flutter#73]
ApiRequests shows adding torrent url and rss url with no url validation. Even an empty url shows no warning/error.

@harchani-ritik I propose to improve this by creating a validation logic for the urls and show a proper error message to the user in the UI if the url is empty.

**Comment by harchani-ritik** [comment]
Yeah, this is required.

**Comment by rj-since-2000** [comment]
@harchani-ritik Should I validate using standard url regex or just check for empty urls?

**Comment by tusharojha** [comment]
Hi @rj-since-2000 
I would suggest using RegEX to verify the format. Also, make sure to accept the IP addresses too.

**Comment by rj-since-2000** [comment]
The regex validates -

```
https://blasanka.github.io/
www.google.com
facebook.com
http://example.com/method?param=flutter
stackoverflow.com
https://github.com/dart-lang/dart-pad/wiki/Sharing-Guide
192.168.29.198
```
Verify it here: https://dartpad.dev/3d547fa15849f9794b7dbb8627499b00
