### ISSUE TITLE
Incorrect use of ParentDataWidget in History screen

### ISSUE THREAD

**Issue by rj-since-2000** [CCExtractor/rutorrent-flutter#91]
An Expanded widget must be a descendant of a Row, Column, or Flex, and the path from the Expanded widget to its enclosing Row, Column, or Flex must contain only StatelessWidgets or StatefulWidgets (not other kinds of widgets, like RenderObjectWidgets).

In this case if the history items list is empty, then a SVG image is build at the center of an expanded widget which is not a child of a Flex widget which causes an `Exception caught by widgets library` in History screen.

@harchani-ritik I propose to resolve this issue using an appropriate Flex widget as an ancestor of Expanded widget.

**Comment by nb9960** [comment]
PR #85 will fix this, most probably, as I'd removed Expanded widget and while testing I didn't found this issue.

**Comment by harchani-ritik** [comment]
@rj-since-2000 Please check if it's fixed and close the issue.

**Comment by rj-since-2000** [comment]
> @rj-since-2000 Please check if it's fixed and close the issue.

Most probably it's fixed. I have reviewed the code changes in #85 and it's fixed so i'll close this issue.
