### ISSUE TITLE
UI/UX improvements

### ISSUE THREAD

**Issue by rj-since-2000** [CCExtractor/rutorrent-flutter#93]
Currently the app UI has few unnecessary padding and widgets, and lacks minute detailing in the UI. Also some widgets need UX improvements like closing gestures and typical widget flow in the app. Improvements related to it will be resolved here without touching any major business logic or API.

List of improvements -

- [x] Removed unnecessary padding in AppBottomSheet.
- [x] Removed unnecessary padding in SortBottomSheet and pop it on value selection.
- [x] Made the ruTorrent logo still while scrolling in drawer, removed unnecessary padding and code refactoring. 
- [x] Add a clear option button in SortBottomSheet
- [x] "Looking up a deactivated widget's ancestor is unsafe" issue on selecting `No` in SettingsPage -> _logoutAllAccounts dialog. Stability issue of the state of the widget's ancestor.
- [x] A RenderFlex overflowed issue in SortBottomSheet in smaller screen devices
- [x] History status in the trailing container in each tile of history screen is not aligned to center

**Comment by bhaskarblaster** [comment]
I would like to work on it.
