### ISSUE TITLE
Clear selection option for sort by torrents list 

### ISSUE THREAD

**Issue by tusharojha** [CCExtractor/rutorrent-flutter#97]
## Description

In the torrents list page, we can sort by a list of options but there is no way we can remove this sorting. I think we can add a small `clear selection` option to achieve it.

![photo_2021-03-16_02-12-24](https://user-images.githubusercontent.com/36601970/111218799-3b1e6580-85fd-11eb-885f-727905793eb8.jpg)

@harchani-ritik Let me know if I can work on this issue.

**Comment by rj-since-2000** [comment]
@tusharojha This issue will be fixed in #93.

**Comment by tusharojha** [comment]
Hi @rj-since-2000!
Sorry but I haven't seen any code related to it. Also, it's a basic thing to add a proper description for your issues and pull requests. 

Closing this issue now.

**Comment by rj-since-2000** [comment]
> Hi @rj-since-2000!
> Sorry but I haven't seen any code related to it. Also, it's a basic thing to add a proper description for your issues and pull requests.
> 
> Closing this issue now.
@tusharojha 
Agree to that, my bad, I have now added a list of improvements in there.
