### ISSUE TITLE
Navigator PushName should be added for refactoring

### ISSUE THREAD

**Issue by bhaskarblaster** [CCExtractor/rutorrent-flutter#99]
Code will be more refactored for transitioning between pages.

**Comment by harchani-ritik** [comment]
@bhaskarblaster Do you intend to use named routes for a cleaner navigation?

**Comment by bhaskarblaster** [comment]
Yeah I can make the whole project named routes friendly for cleaner navigation.

**Comment by rj-since-2000** [comment]
I would suggest using [auto_route](https://pub.dev/packages/auto_route) for cleaner navigation as it uses code generation to simplify routes setup which requires a minimal amount of code to generate everything needed for navigation inside the app.

**Comment by harchani-ritik** [comment]
@bhaskarblaster Are you still working on this?

**Comment by rj-since-2000** [comment]
> @bhaskarblaster Are you still working on this?

@harchani-ritik Since there's no response, I'm closing this.
